twig:
    default_path: '%kernel.project_dir%/templates'
    # Insérer Bootstrap 
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/public/img': image
        # point this wherever your css files live
        '%kernel.project_dir%/public/css': style
        # récupérer les images du dossier upload
        '%kernel.project_dir%/public/upload': upload
    
when@test:
    twig:
        strict_variables: true
